export const DELETE_CONNECTION_CLIENT = "LIST/DELETE_CONNECTION_CLIENT"
export const SET_CLIENT_LIST = "LIST/SET_TO_CLIENT"
export const ADD_CLIENT_LIST = "LIST/ADD_TO_CLIENT"
export const DELETE_CONNECTION_SERVER = "LIST/DELETE_CONNECTION_SERVER"
export const SET_SERVER_LIST = "LIST/SET_TO_SERVER"
export const ADD_SERVER_LIST = "LIST/ADD_TO_SERVER"




