export const DELETE_CONNECTION_CLIENT = "LIST/DELETE_CONNECTION_CLIENT";
export const SET_CLIENT_LIST = "LIST/SET_TO_CLIENT";
export const ADD_CLIENT_LIST = "LIST/ADD_TO_CLIENT";
export const SET_SERVER_LIST = "LIST/SET_TO_SERVER";
export const SET_LOGGED = "APP/SET_LOGGED";
export const SET_LOADING = "APP/SET_LOADING";
export const SHOW_MESSAGE = "APP/SHOW_MESSAGE";
export const SET_TERMINAL_LINK = "APP/ET_TERMINAL_LINK";
